#!/usr/bin/env php

<?php require 'clip.php';

//Load all the commands into Clip
\Clip\Main::load($argv[0]);

$offset = 2; //Accounts for script name and command name to determine parameters
$argc < $offset ? \Clip\Main::help() : \Clip\Main::command($argv[$offset-1], array_slice($argv, $offset));
